spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cinema_db?useUnicode=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

server:
  port: 9191